# Generated by Django 4.2.1 on 2023-05-11 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_delete_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=250)),
                ('difficulty_rating', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty_rating',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='type',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('N', 'no equipment'), ('B', 'barbells'), ('Y', 'a yoga mat'), ('D', 'dumbells'), ('R', 'resistance bands'), ('T', 'TRX bands')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
        ),
    ]
