# Generated by Django 4.2.1 on 2023-05-14 21:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0003_workout_remove_exercise_difficulty_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('resistance', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('reps', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='type',
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('U', 'unspecified'), ('W', 'warmup'), ('Y', 'yoga'), ('S', 'stretching'), ('A', 'agility'), ('F', 'strength'), ('R', 'rehabilitation'), ('C', 'cardio')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(default='No description provided', max_length=250),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('N', 'no equipment'), ('M', 'a machine'), ('B', 'barbells'), ('Y', 'yoga equipment'), ('D', 'dumbells'), ('R', 'resistance bands'), ('T', 'TRX bands')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='Unnamed Exercise', max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='difficulty_rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_time', models.IntegerField(default=60)),
                ('notes', models.TextField(default='', max_length=250)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('sets', models.ManyToManyField(blank=True, to='workouts.set')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='set',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workout'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic_url', models.CharField(blank=True, max_length=200, null=True)),
                ('exercises', models.ManyToManyField(blank=True, related_name='profiles', to='workouts.exercise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workouts', models.ManyToManyField(blank=True, related_name='profiles', to='workouts.workout')),
            ],
        ),
    ]
