# Generated by Django 4.2.1 on 2023-05-16 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_set_remove_exercise_workout_remove_workout_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.profile')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
            options={
                'unique_together': {('profile', 'workout')},
            },
        ),
    ]
