# Generated by Django 4.2.1 on 2023-05-17 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_remove_workoutexercise_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='workouts',
        ),
        migrations.DeleteModel(
            name='ProfileWorkout',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
        migrations.AddField(
            model_name='profile',
            name='exercises',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='workouts.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='workouts',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='workouts.workout'),
            preserve_default=False,
        ),
    ]
