# Generated by Django 4.2.1 on 2023-05-18 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0012_remove_profile_exercises_remove_profile_workouts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='exercises',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='workouts',
        ),
        migrations.AddField(
            model_name='profile',
            name='exercises',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='profile',
            name='workouts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='workouts.workout'),
        ),
    ]
