# Generated by Django 4.2.1 on 2023-05-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_remove_profile_exercises_remove_profile_workouts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='workouts.exercise'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workouts',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='workouts.workout'),
        ),
    ]
